#!/usr/bin/env python3
"""Reproduce Task 2 metrics used to audit the first-pass AI analysis."""

from __future__ import annotations

import csv
import json
import math
import os
from collections import defaultdict
from pathlib import Path
from statistics import mean


ROOT = Path(__file__).resolve().parents[1]
RUN_DATE = os.environ.get("HW05_RUN_DATE", "20260901")
SCENARIOS = ("Load", "Stress", "Spike", "Soak")
FINAL_LABEL = "FR06 View imported product detail"


def percentile(values: list[float], quantile: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    return ordered[max(0, math.ceil(quantile * len(ordered)) - 1)]


def stage_name(thread_name: str) -> str:
    head, separator, tail = thread_name.rpartition(" ")
    if separator and "-" in tail and all(part.isdigit() for part in tail.split("-", 1)):
        return head
    return thread_name


def sample_metrics(rows: list[dict[str, str]]) -> dict[str, float | int]:
    elapsed = [float(row["elapsed"]) for row in rows]
    failures = sum(row["success"].strip().lower() != "true" for row in rows)
    starts = [float(row["timeStamp"]) for row in rows]
    ends = [float(row["timeStamp"]) + float(row["elapsed"]) for row in rows]
    window = max((max(ends) - min(starts)) / 1000.0, 0.001) if rows else 0.001
    completed = sum(
        row["label"] == FINAL_LABEL and row["success"].strip().lower() == "true"
        for row in rows
    )
    return {
        "samples": len(rows),
        "failures": failures,
        "error_percent": round(100.0 * failures / len(rows), 4) if rows else 0.0,
        "mean_ms": round(mean(elapsed), 3) if elapsed else 0.0,
        "p90_ms": percentile(elapsed, 0.90),
        "p95_ms": percentile(elapsed, 0.95),
        "p99_ms": percentile(elapsed, 0.99),
        "min_ms": min(elapsed, default=0.0),
        "max_ms": max(elapsed, default=0.0),
        "window_seconds": round(window, 3),
        "sample_rate_s": round(len(rows) / window, 3),
        "completed_workflows": completed,
        "completed_workflow_rate_s": round(completed / window, 3),
    }


def quarter(values: list[float], first: bool) -> list[float]:
    size = max(1, math.ceil(len(values) / 4))
    return values[:size] if first else values[-size:]


def resource_metrics(path: Path) -> dict[str, float | int]:
    with path.open(newline="", encoding="utf-8") as stream:
        rows = list(csv.DictReader(stream))
    cpu = [float(row["cpu_percent"]) for row in rows]
    rss_mb = [float(row["rss_kb"]) / 1024.0 for row in rows]
    return {
        "observations": len(rows),
        "cpu_mean_percent": round(mean(cpu), 3),
        "cpu_peak_percent": max(cpu),
        "cpu_first_quarter_mean_percent": round(mean(quarter(cpu, True)), 3),
        "cpu_last_quarter_mean_percent": round(mean(quarter(cpu, False)), 3),
        "rss_start_mb": round(rss_mb[0], 3),
        "rss_peak_mb": round(max(rss_mb), 3),
        "rss_final_mb": round(rss_mb[-1], 3),
        "rss_first_quarter_mean_mb": round(mean(quarter(rss_mb, True)), 3),
        "rss_last_quarter_mean_mb": round(mean(quarter(rss_mb, False)), 3),
    }


def main() -> None:
    analysis: dict[str, dict] = {}
    for scenario in SCENARIOS:
        stem = f"23127035_{scenario}_{RUN_DATE}"
        jtl_path = ROOT / "results" / f"{stem}.jtl"
        resource_path = ROOT / "evidence" / "resource" / f"{stem}_backend_resource.csv"
        with jtl_path.open(newline="", encoding="utf-8") as stream:
            rows = list(csv.DictReader(stream))

        grouped_stages: dict[str, list[dict[str, str]]] = defaultdict(list)
        grouped_labels: dict[str, list[dict[str, str]]] = defaultdict(list)
        for row in rows:
            grouped_stages[stage_name(row["threadName"])].append(row)
            grouped_labels[row["label"]].append(row)

        analysis[scenario] = {
            "source_jtl": str(jtl_path.relative_to(ROOT)),
            "overall": sample_metrics(rows),
            "stages": {name: sample_metrics(values) for name, values in grouped_stages.items()},
            "labels": {name: sample_metrics(values) for name, values in grouped_labels.items()},
            "resources": resource_metrics(resource_path),
        }

    output_json = ROOT / "analysis" / "task2_metrics.json"
    output_json.write_text(json.dumps(analysis, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# HW05 Task 2 - Authoritative Raw-Log Metrics",
        "",
        "Generated by `scripts/analyze_task2.py`. Percentiles use nearest rank over JMeter `elapsed`. A completed workflow is counted only when the successful final sampler `FR06 View imported product detail` is present. Rates use the earliest-request to latest-response window within the reported scope.",
        "",
        "| Scenario | HTTP samples | Failed | Error % | p95 ms | p99 ms | Max ms | Samples/s | Completed workflows | Completed workflows/s |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for scenario in SCENARIOS:
        item = analysis[scenario]["overall"]
        lines.append(
            f"| {scenario} | {item['samples']:,} | {item['failures']} | {item['error_percent']:.2f} | "
            f"{item['p95_ms']:.0f} | {item['p99_ms']:.0f} | {item['max_ms']:.0f} | "
            f"{item['sample_rate_s']:.2f} | {item['completed_workflows']:,} | "
            f"{item['completed_workflow_rate_s']:.2f} |"
        )

    lines.extend([
        "",
        "## Stage metrics",
        "",
        "| Scenario/stage | Samples | Failed | p95 ms | p99 ms | Samples/s | Completed workflows |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ])
    for scenario in SCENARIOS:
        for name, item in analysis[scenario]["stages"].items():
            lines.append(
                f"| {scenario}: {name} | {item['samples']:,} | {item['failures']} | "
                f"{item['p95_ms']:.0f} | {item['p99_ms']:.0f} | {item['sample_rate_s']:.2f} | "
                f"{item['completed_workflows']:,} |"
            )

    lines.extend([
        "",
        "## Backend process resources",
        "",
        "CPU is the macOS percentage for the exact Node PID and is not normalized across the ten cores. RSS is resident memory. First/last-quarter means are descriptive observations, not a leak test or an absolute ceiling.",
        "",
        "| Scenario | CPU mean % | CPU peak % | CPU Q1/Q4 mean % | RSS start MB | RSS peak MB | RSS final MB | RSS Q1/Q4 mean MB |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ])
    for scenario in SCENARIOS:
        item = analysis[scenario]["resources"]
        lines.append(
            f"| {scenario} | {item['cpu_mean_percent']:.2f} | {item['cpu_peak_percent']:.1f} | "
            f"{item['cpu_first_quarter_mean_percent']:.2f} / {item['cpu_last_quarter_mean_percent']:.2f} | "
            f"{item['rss_start_mb']:.2f} | {item['rss_peak_mb']:.2f} | {item['rss_final_mb']:.2f} | "
            f"{item['rss_first_quarter_mean_mb']:.2f} / {item['rss_last_quarter_mean_mb']:.2f} |"
        )

    output_md = ROOT / "analysis" / "task2_metrics.md"
    output_md.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(output_json)
    print(output_md)


if __name__ == "__main__":
    main()
